example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_mywatchlist
from mywatchlist.views import show_html
from mywatchlist.views import show_xml
from mywatchlist.views import show_json

app_name = 'mywatchlist'

urlpatterns = [
    path('html/', show_html, name='show_html'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('', show_mywatchlist, name='show_mywatchlist'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path

# Register, Login, Logout
from todolist.views import register
from todolist.views import login_user
from todolist.views import logout_user

from todolist.views import create_task
from todolist.views import delete_task
from todolist.views import add_task
from todolist.views import change_status

from todolist.views import show_todolist_ajax
from todolist.views import show_json

app_name = 'todolist'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),

    path('create-task/', create_task, name='create_task'),
    path('delete-task/<int:id>', delete_task, name='delete_task'),
    path('add-task/', add_task, name='add_task'),
    path('change-status/<int:id>', change_status, name='change_status'),

    path('', show_todolist_ajax, name='show_todolist_ajax'),
    path('json/', show_json, name='show_json'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

class MyWatchlist(models.Model):
    watched = models.BooleanField()
    title = models.TextField()
    rating = models.IntegerField()
    release_date = models.TextField()
    review = models.TextField()

todolist/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(default=timezone.now)
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms

class FormTask(forms.Form):
    title = forms.CharField(label="Title")
    description = forms.CharField(label="Description", widget=forms.Textarea)

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

def show_katalog(request):
    data_barang_katalog = CatalogItem.objects.all()
    context = {
    'list_barang': data_barang_katalog,
    'nama': 'Vania Azria Wardani',
    'id': '2106650380'
    }

    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyWatchlist
from django.http import HttpResponse
from django.core import serializers

def show_mywatchlist(request):
    data_barang_mywatchlist = MyWatchlist.objects.all()
    
    watched = 0
    unwatched = 0
    text = ""

    for movie in data_barang_mywatchlist:
        if (movie.watched):
            watched += 1
        else:
            unwatched += 1

    if (watched >= unwatched):
        text = "Selamat, kamu sudah banyak menonton!"
    else:
        text = "Wah, kamu masih sedikit menonton!"
    
    context = {
    'list_barang': data_barang_mywatchlist,
    'nama': 'Vania Azria Wardani',
    'id': '2106650380',
    'text': text
    }

    return render(request, "mywatchlist.html", context)

def show_html(request):
    data_barang_mywatchlist = MyWatchlist.objects.all()
    
    watched = 0
    unwatched = 0
    text = ""

    for movie in data_barang_mywatchlist:
        if (movie.watched):
            watched += 1
        else:
            unwatched += 1

    if (watched >= unwatched):
        text = "Selamat, kamu sudah banyak menonton!"
    else:
        text = "Wah, kamu masih sedikit menonton!"
    
    context = {
    'list_barang': data_barang_mywatchlist,
    'nama': 'Vania Azria Wardani',
    'id': '2106650380',
    'text': text
    }

    return render(request, "mywatchlist.html", context)
    
def show_xml(request):
    data = MyWatchlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = MyWatchlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from todolist.forms import FormTask
from todolist.models import Task
from django.http import HttpResponseRedirect, HttpResponse, HttpRequest
from django.urls import reverse
from django.core import serializers

# @login_required(login_url='/todolist/login/')
# def show_todolist(request):
#     data_task = Task.objects.filter(user=request.user).all()
#     context = {'task': data_task}
#     return render(request, "todolist.html", context)

@login_required(login_url='/todolist/login/')
def show_todolist_ajax(request):
    data = Task.objects.filter(user=request.user).all()
    context = {
        'todo_list': data,
    } 
    return render(request, "todolist_ajax.html", context)

def show_json(request):
    data = Task.objects.filter(user=request.user).all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def add_task(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        new_task = Task(
            title=title, 
            description=description,
            user=request.user,
        )
        new_task.save()
    return redirect('todolist:show_todolist_ajax')

def create_task(request):
    form = FormTask()
    if request.method == "POST":
        form = FormTask(request.POST)
        if form.is_valid():
            form = Task(
                title=form.cleaned_data["title"],
                description=form.cleaned_data["description"],
                user=request.user,
            )
            form.save()
            return redirect("todolist:show_todolist")

    context = {'form': form}
    return render(request, "create_task.html", context)

def delete_task(request, id):
    Task.objects.get(pk=id).delete()
    return redirect('todolist:show_todolist_ajax')

def change_status(request, id):
    task = Task.objects.get(pk=id) 
    if (not task.is_finished):
        task.is_finished = True
    task.save()
    return redirect('todolist:show_todolist_ajax')

def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account has been created successfully!')
            return redirect('todolist:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('todolist:show_todolist_ajax')
        else:
            messages.info(request, 'Wrong username or password:(')
    return render(request, 'login.html')

def logout_user(request):
    logout(request)
    messages.info(request, 'Logout Successful')
    return redirect('todolist:login')

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{id}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for barang in list_barang %}
      <tr>
        <th>{{barang.item_name}}</th>
        <th>{{barang.item_price}}</th>
        <th>{{barang.item_stock}}</th>
        <th>{{barang.rating}}</th>
        <th>{{barang.description}}</th>
        <th>{{barang.item_url}}</th>
      </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Assignment 3 PBP</h1>

  <h4>Name: </h4>
  <p>{{nama}}</p>

  <h4>Student ID: </h4>
  <p>{{id}}</p>

  <h4>Status: </h4>
  <p>{{text}}</p>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for barang in list_barang %}
      <tr>
        <th>{{barang.watched}}</th>
        <th>{{barang.title}}</th>
        <th>{{barang.rating}}</th>
        <th>{{barang.release_date}}</th>
        <th>{{barang.review}}</th>
      </tr>
    {% endfor %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Create New Task</title>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
<style>
  head, body {
    font-family: 'Montserrat', sans-serif;
    height: 100vh;
  }

  body {
    align-items: center;
    background: linear-gradient(rgb(178, 233, 255), rgb(89, 131, 230));
    background-size: 100% 100%;
    background-attachment: fixed;
  }
</style>
{% endblock meta %}

{% block content %}
<div class="create w-100 m-auto text-center">
  <nav class="navbar navbar-dark bg-dark mb-5">
    <div class="container-fluid">
        <h1 class="navbar-brand fw-bold mb-2 mt-2 text-light">Welcome, {{user.get_username}}!</h1>
        <button class="btn btn-primary btn-md fw-bold" type="button" onclick="location.href='/todolist/logout'">Logout</button>
    </div>
  </nav>
  <div class="create-task w-100 m-auto text-center" style="max-width: 750px">
    <h1 class="h1 mb-3 text-primary fw-bold">Create Task</h1>
    <form method="POST" style="text-align:start">
      {% csrf_token %}
      <table>
        {{ form.as_table }}
      </table>
      <input class="btn btn-lg btn-primary w-100 mt-4 fw-bold" type="submit" value="Create"/></input>
    </form>
    {% if messages %}
    {% for message in messages %}
        <p class="text-light">{{ message }}</p>
    {% endfor %}
    {% endif %}
  </div>
</div>
{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
<style>
  head, body {
    font-family: 'Montserrat', sans-serif;
    height: 100vh;
  }

  body {
    display: flex;
    align-items: center;
    background: linear-gradient(rgb(178, 233, 255), rgb(89, 131, 230));
    background-size: 100% 100%;
    background-attachment: fixed;
  }
</style>
{% endblock meta %}

{% block content %}
<div class="container login w-100 m-auto" style="max-width: 750px">
  <h1 class="mb-4 fw-bold text-primary text-center">Login</h1>
  <form method="POST">
    {% csrf_token %}
    <div class="username-form mb-4">
      <label for="username" class="form-label fw-semibold">Username</label>
      <input type="text" class="form-control shadow" name="username" id="username" placeholder="Username">
    </div>
    <div class="password-form mb-4">
      <label for="password" class="form-label fw-semibold">Password</label>
      <input type="password" class="form-control shadow" name="password" id="password" placeholder="Password">
    </div>
    {% if messages %}
      {% for message in messages %}
          <p class="text-light">{{ message }}</p>
      {% endfor %}
    {% endif %}     
    <input class="btn btn-lg btn-primary w-100 mt-2 fw-bold" type="submit" value="Login"></input>
    <p class="mt-3 mb-3 text-center">Belum mempunyai akun? <a class = "text-light fw-semibold" href="{% url 'todolist:register' %}">Buat akun</a></p>
  </form>
</div>
{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Register</title>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
<style>
  head, body {
    font-family: 'Montserrat', sans-serif;
    height: 100vh;
  }

  body {
    display: flex;
    align-items: center;
    background: linear-gradient(rgb(178, 233, 255), rgb(89, 131, 230));
    background-size: 100% 100%;
    background-attachment: fixed;
  }
</style>
{% endblock meta %}

{% block content %}
<div class="container register w-100 m-auto" style="max-width: 750px">
  <h1 class="mb-4 fw-bold text-primary text-center">Register</h1>
  <form method="POST">
    {% csrf_token %}
    <table>  
      {{ form.as_table }}  
    </table>  
    <input class="btn btn-lg btn-primary w-100 mt-4 fw-bold" type="submit" value="Register"/></input>
    {% if messages %}
      {% for message in messages %}
          <p class="text-light">{{ message }}</p>
      {% endfor %}
    {% endif %}
  </form>
{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
<title>To Do List</title>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
<style>
  head, body {
    font-family: 'Montserrat', sans-serif;
    height: auto;
  }

  body {
    align-items: center;
    background: linear-gradient(rgb(178, 233, 255), rgb(89, 131, 230));
    background-size: 100% 100%;
    background-attachment: fixed; 
  }

  .card:hover{
    transform:rotateZ(15deg);
    box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
  }
</style>
{% endblock meta %}

{% block content %}
<div class="todo w-100 m-auto text-center">
  <nav class="navbar navbar-dark bg-dark mb-5">
    <div class="container-fluid">
        <h1 class="navbar-brand fw-bold mb-2 mt-2 text-light">Welcome, {{user.get_username}} !</h1>
        <button class="btn btn-primary btn-md fw-bold" type="button" onclick="location.href='/todolist/logout'">Logout</button>
    </div>
  </nav>
  <div class="todolist text-center">
    <h2 class="h1 mb-3 text-primary fw-bold">To Do List</h2>
    <div class="container">
      <div class="row row-cols-1 g-4 m-auto">
        {% for task in task %}
        <div class="col">
          <div class="card border-primary shadow m-auto h-100" style="width:20rem;">
            <div class="card-header">
              <h6 class="card-subtitle">{{task.date}}</h6>
            </div>
            <div class="card-body">
              <h4 class="card-title fw-bold">{{task.title}}</h4>    
              <p class="card-text">{{task.description}}</p>
            </div>
            <ul class="list-group list-group-flush">
              {% if task.is_finished %}
              <li class="list-group-item text-primary fw-semibold">Finished</li>
              {% else %}
              <li class="list-group-item text-primary fw-semibold">Not Finished</li>
              {% endif %}
            </ul>
            <div class="card-footer">
              <a class="text-light fw-semibold; btn btn-dark btn-sm" href="{% url 'todolist:status' task.id %}">Change</a></button>
              <a class="text-light fw-semibold; btn btn-danger btn-sm" href="{% url 'todolist:delete' task.id %}">Delete</a></button>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <button type="button" class="btn btn-primary btn-lg mt-4 mb-4 fw-bold" onclick="location.href='/todolist/create-task'">Create New Task</button> 
</div>
{% endblock content %}

todolist/templates/todolist_ajax.html
{% extends 'base.html' %}

{% block meta %}
    <title>To Do List</title>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <style>
        head, body{
            font-family: 'Montserrat', sans-serif;
            height: 100vh;
        }
        .card {
            box-shadow: 0 4px 8px 0 rgb(89, 131, 230);
            transition: 0.3s;
            width: 40%;    
            border-radius: 5px;
            background-color: rgb(252, 245, 95);
        }
            
        .card:hover {
            transform: scale(1.05);
            box-shadow: 0 10px 20px rgb(89, 131, 230), 0 4px 8px rgb(89, 131, 230); 
            background-color: rgb(77, 95, 217); 
            color: rgb(252, 245, 95);  
        }
        
        .container {
            padding: 2px 16px;
        }
            
        .content {
            padding-left: 15px;
            padding-right: 15px;
        }

        body {
            display: flex;
            align-items: center;
            background: linear-gradient(rgb(178, 233, 255), rgb(89, 131, 230));
            background-size: 100% 100%;
            background-attachment: fixed;
        }

        input, textarea {
            padding: 0.5rem;
            border: 1px solid;
            border-radius: 8px;
            width: 100%
        } 
    </style>
{% endblock meta %}

{% block content %}
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        function posting(e) {
          e.preventDefault()
          const title = $("#title").val()
          const description = $("#description").val()
          
          const data = {
            title: title,
            description: description,
            csrfmiddlewaretoken: "{{ csrf_token }}"
          }
          
          $.ajax({
            type: 'POST',
            url: '{% url "todolist:add_task" %}',
            data: data,
            dataType: 'json'
          });

          fetchData();
        }
      
        function update(data) {
          const myElement = $("#main-div")
          myElement.html('');
          for (let i = 0; i < data.length; i++) {
            let message = (data[i].fields.is_finished) ? 'Done':'Not Done';
            let color = (data[i].fields.is_finished) ? 'green':'red';
            myElement.append(`
              <div class="card col-sm-4 mb-1 mt-4 mx-auto" style="width: 18rem;">
                <div class="card-body">
                  <h4 class="card-title text-center fw-semibold">${data[i].fields.title}</h4>
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item text-secondary">${data[i].fields.date}</li>
                    <li class="list-group-item">${data[i].fields.description}</li>
                  </ul>
                </div>
                <div class="card-footer text-center">
                  <p style="font-weight:bold; color:${color};">${message}</p>
                  <a class="text-light fw-semibold; btn btn-dark btn-sm" href="change-status/${data[i].pk}" style="text-decoration:solid ">Finish Task</a></button>
                  <a class="text-light fw-semibold; btn btn-danger btn-sm" href=" delete-task/${data[i].pk}" style="text-decoration:solid ">Delete Task</a></button>
                </div>
              </div>
            `)
          }
        }
        function fetchData() {
          $.get("/todolist/json", update)
        }
      
        $(document).ready(() => {
          $("#create-button").click(posting)
          fetchData()
        })
    </script>
  </head>
  
  <header>
    <nav class="navbar navbar-expand-lg bg-light bg-gradient fixed-top" style="padding: auto;">
      <div class="container-fluid">
        <a class="navbar-brand fw-bold mb-2 mt-2" href="#main-table">This is your TODO list, {{user.username}}!</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item" style="margin: 5px;">
              <a class="btn btn-primary" data-bs-toggle="modal" href="#addTask" role="button">Add Task</a>
            </li>
            <li class="nav-item" style="margin: 5px;">
              <a class="btn btn-dark" href="{% url 'todolist:logout' %}" role="button">Logout</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <div style="padding:5px;"></div>
  
  <div class="row row-cols-1 row-cols-md-3 g-4 md:justify-end gap-4" id="main-div"></div>
  
  <div class="modal fade" id="addTask" tabindex="-1" aria-labelledby="addTaskLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5 fw-bold" id="exampleModalLabel">Add New Task</h1>
        </div>
        <div class="modal-body">
          <form method="POST" action="" style="display: inline-block;">
            {% csrf_token %}
            <table>
                <tr>
                  <label>Title</label>
                  <input type="text" name="title" id="title">
                </tr>
                <tr>
                  <label>Description</label>
                  <input type="textarea" name="description" id="description">
                </tr>
                    <td colspan="2">
                      <input data-bs-dismiss="modal" style="width: 100%; margin-top: 20px; margin-bottom: 7px;" class="btn btn-primary" type="submit" name="submit" value="Create" id="create-button">
                    </td>
                </tr>
            </table>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>


{% endblock content %}